# Generated by Django 5.2.9 on 2026-02-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dashboard', '0007_passenger'),
        ('app_operator', '0010_seats_seat_position_seats_seat_price_alter_seats_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.seats')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.trip')),
            ],
        ),
    ]
