# Generated by Django 5.2.9 on 2026-02-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
