# Generated by Django 5.2.9 on 2026-02-18 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0011_alter_operator_contact_alter_passenger_contact'),
        ('app_operator', '0010_seats_seat_position_seats_seat_price_alter_seats_bid_and_more'),
        ('app_passenger', '0002_booking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='pending', max_length=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.trip')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.seats')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app_passenger.bookingmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
