# Generated by Django 5.2.9 on 2026-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(unique=True)),
                ('contact', models.IntegerField(unique=True)),
            ],
        ),
    ]
