# Generated by Django 5.2.9 on 2026-01-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_operatorpro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatorPro',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='user_name',
        ),
    ]
