# Generated by Django 5.2.9 on 2026-01-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0005_busreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusReg',
        ),
    ]
