# Generated by Django 5.2.9 on 2026-02-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_alter_district_name'),
        ('app_dashboard', '0008_operator_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='dis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.district'),
        ),
    ]
