# Generated by Django 5.2.9 on 2026-02-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0010_alter_operator_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
