# Generated by Django 5.2.9 on 2026-03-05 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BusReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=15, unique=True)),
                ('con', models.CharField(max_length=15)),
                ('seat_type', models.CharField(choices=[('2x2', '2 x 2'), ('2x3', '2 x 3')], max_length=5)),
                ('total_rows', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('bid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_operator.busreg')),
                ('rid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_operator.routes')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.routes')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatno', models.CharField(max_length=15)),
                ('seat_price', models.DecimalField(decimal_places=2, default=742.0, max_digits=7)),
                ('seat_position', models.CharField(blank=True, choices=[('window', 'Window'), ('aisle', 'Aisle'), ('middle', 'Middle')], max_length=10, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.busreg')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed')], default='scheduled', max_length=10)),
                ('busroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.busroutes')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.location')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_operator.trip')),
            ],
        ),
    ]
