# Generated by Django 5.2.9 on 2026-01-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
