# Generated by Django 5.2.9 on 2026-01-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0003_alter_busreg_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('bid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_operator.busreg')),
                ('rid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_operator.routes')),
            ],
        ),
    ]
