# Generated by Django 5.2.9 on 2026-01-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0004_busroutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroutes',
            name='ts',
            field=models.TimeField(),
        ),
    ]
