# Generated by Django 5.2.9 on 2026-01-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0005_alter_busroutes_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busroutes',
            old_name='ts',
            new_name='time',
        ),
    ]
