# Generated by Django 5.2.9 on 2026-01-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0006_rename_ts_busroutes_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatno', models.CharField(max_length=15)),
                ('bid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_operator.busreg')),
            ],
        ),
    ]
