# Generated by Django 5.2.9 on 2026-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0007_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreg',
            name='seat_type',
            field=models.CharField(choices=[('2x2', '2 x 2'), ('2x3', '2 x 3')], default='2x2', max_length=3),
        ),
        migrations.AddField(
            model_name='busreg',
            name='total_rows',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='seats',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
