# Generated by Django 5.2.9 on 2026-01-29 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operator', '0008_busreg_seat_type_busreg_total_rows_seats_is_booked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreg',
            name='seat_type',
            field=models.CharField(choices=[('2x2', '2 x 2'), ('2x3', '2 x 3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='busreg',
            name='total_rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='busreg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
