# Generated by Django 5.2.9 on 2026-02-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_alter_district_name'),
        ('app_operator', '0009_alter_busreg_seat_type_alter_busreg_total_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='seat_position',
            field=models.CharField(blank=True, choices=[('window', 'Window'), ('aisle', 'Aisle'), ('middle', 'Middle')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seats',
            name='seat_price',
            field=models.DecimalField(decimal_places=2, default=742.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='seats',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.busreg'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed')], default='scheduled', max_length=10)),
                ('busroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_operator.busroutes')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.location')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_operator.trip')),
            ],
        ),
    ]
